import{i as l,S as m,N as p,K as h,M as f,a as g}from"./assets/vendor-UvMvCI1P.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const i=document.getElementById("contactForm"),d=document.getElementById("interestModal"),v=document.getElementById("closeModal");i.addEventListener("submit",async function(t){t.preventDefault();const s=i.elements["user-email"].value.trim();i.elements["user-comment"].value.trim();try{const o=await fetch("https://portfolio-js.b.goit.study/api/requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:s})});if(console.log(o),o.status===201)d.classList.remove("hidden"),i.reset();else{const n=await o.json();console.log("Помилка з сервера:",n),alert("Oops! Something went wrong. Please check your input and try again.")}}catch(o){l.error({message:"Network error! Please try again later.",position:"topRight"}),console.error(o)}});v.addEventListener("click",function(){d.classList.add("hidden")});document.addEventListener("DOMContentLoaded",()=>{const t=document.getElementById("theme-toggle-checkbox");localStorage.getItem("theme")==="dark"&&(document.body.classList.add("dark-theme"),t.checked=!0),t.addEventListener("change",()=>{t.checked?(document.body.classList.add("dark-theme"),localStorage.setItem("theme","dark")):(document.body.classList.remove("dark-theme"),localStorage.setItem("theme","light"))})});const y=document.querySelector(".burger"),c=document.querySelector(".mobile-menu"),w=document.querySelector(".close-menu"),b=document.querySelectorAll(".mobile-nav-list a");y.addEventListener("click",()=>{c.classList.remove("visually-hidden"),document.body.classList.add("no-scroll")});w.addEventListener("click",()=>{c.classList.add("visually-hidden"),document.body.classList.remove("no-scroll")});b.forEach(t=>{t.addEventListener("click",()=>{c.classList.add("visually-hidden"),document.body.classList.remove("no-scroll")})});const u=document.querySelector(".reviews-list"),L=async()=>{const t="https://portfolio-js.b.goit.study/api/reviews";try{return(await g.get(t)).data}catch(s){l.show({fontSize:"large",position:"topRight",messageColor:"white",timeout:6e3,backgroundColor:"#ED3B44",progressBar:!1,message:"Error while fetching reviews"}),console.error("Error fetching reviews:",s),u.insertAdjacentHTML("beforeend",`
        <li class="not-found-item">
        <p class="not-found-text">Not found</p>
        </li>
        `)}},E=async()=>{const t=await L();if(t){const s=t.map(o=>`
            <li class="reviews-list-item swiper-slide">
                <p class="reviews-text">${o.review}</p>
                <div class="author-information">
                    <img class="author-image" src="${o.avatar_url}" alt="review from ${o.author}" 
                    width="40" height="40" loading="lazy">
                    <p class="name-text">${o.author}</p>
                </div>
            </li>
        `).join("");u.insertAdjacentHTML("beforeend",s)}};E();new m(".reviews .swiper",{modules:[p,h,f],mousewheel:{enabled:!0,invert:!0},keyboard:{enabled:!0},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},breakpoints:{360:{slidesPerView:1},768:{slidesPerView:1},1280:{slidesPerView:2,spaceBetween:32}}});
//# sourceMappingURL=index.js.map
